#!/usr/bin/env bash
# shellcheck shell=bash

# pfsense-backup: run the full test suite.
#
# Copyright (C) 2025 James Hanlon [mailto:jim@hanlonsoftware.com]
# SPDX-License-Identifier: AGPL-3.0-or-later

set -euo pipefail

whereami=$(dirname "$(readlink -f "${BASH_SOURCE[0]}")")

bats \
    "${whereami}/01-build.bats" \
    "${whereami}/02-pfsense-backup.bats" \
    "${whereami}/03-backup-required-vars.bats" \
    "${whereami}/04-backup-success.bats" \
    "${whereami}/05-backup-encryption.bats" \
    "${whereami}/06-backup-aws-failure.bats" \
    "${whereami}/07-backup-xml-validation.bats" \
    "${whereami}/08-healthcheck.bats"
