#!/usr/bin/env bash

# An application specific service to create pfSense backups and copy them off site.
# Copyright (C) 2025 James Hanlon [mailto:jim@hanlonsoftware.com]
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
# 
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
# 
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.

set -o errexit -o errtrace -o nounset -o pipefail
set +o xtrace +o verbose
if is_true "${DEBUG:-false}"; then set -o xtrace -o verbose; fi

ENV=${ENV:-${HOME:-/root}/.env}
# shellcheck disable=SC1090
[[ -r "${ENV}" ]] && source "${ENV}"

# Write cronjob env to file, fill in sensible defaults, and read them back in
cat <<EOF >"${ENV}"
export AWS_CONFIG_FILE='${AWS_CONFIG_FILE:-/run/secrets/aws-config}'
export AWS_DRYRUN='${AWS_DRYRUN:-false}'
export AWS_S3_BUCKET_NAME='${AWS_S3_BUCKET_NAME:?Need bucket}'
export COMPRESSION='${COMPRESSION:-none}'
export CRON_EXPRESSION='${CRON_EXPRESSION:-@daily}'
export DEBUG='${DEBUG:-false}'
export GPG_CIPHER_ALGO='${GPG_CIPHER_ALGO:-aes256}'
export GPG_PASSPHRASE='${GPG_PASSPHRASE:-}'
export GPG_PASSPHRASE_FILE='${GPG_PASSPHRASE_FILE:-/run/secrets/gpg-passphrase}'
export HEALTHCHECK_MAX_AGE_SECONDS='${HEALTHCHECK_MAX_AGE_SECONDS:-172800}'
export HEALTHCHECK_STARTUP_GRACE_SECONDS='${HEALTHCHECK_STARTUP_GRACE_SECONDS:-900}'
export HEALTHCHECK_SUCCESS_FILE='${HEALTHCHECK_SUCCESS_FILE:-/tmp/pfsense-backup.last-success}'
export PFSENSE_HOST='${PFSENSE_HOST:-}'
export PFSENSE_USER='${PFSENSE_USER:-}'
export PFSENSE_IDENTITY_FILE='${PFSENSE_IDENTITY_FILE:-/run/secrets/pfsense-identity}'
export PFSENSE_IDENTITY_PASSWORD='${PFSENSE_IDENTITY_PASSWORD:-}'
export PFSENSE_IDENTITY_PASSWORD_FILE='${PFSENSE_IDENTITY_PASSWORD_FILE:-/run/secrets/pfsense-identity-password}'
export PFSENSE_SSH_KNOWN_HOSTS_FILE='${PFSENSE_SSH_KNOWN_HOSTS_FILE:-/root/.ssh/known_hosts}'
export PFSENSE_SSH_STRICT_HOST_KEY_CHECKING='${PFSENSE_SSH_STRICT_HOST_KEY_CHECKING:-accept-new}'
export RSA_PUBLIC_KEY_FILE='${RSA_PUBLIC_KEY_FILE:=/run/secrets/rsa-public-key}'
export TAILSCALE_HOST='${TAILSCALE_HOST:-}'
export TZ='${TZ:-UTC}'
EOF
clean-credentials() {
    sed -E 's/(GPG_PASSPHRASE|PFSENSE_IDENTITY_PASSWORD)='"'"'.*'"'"'$/\1='"'**REDACTED**'"'/' 
}
info "create env file ${ENV}"
chmod -c 0600 "${ENV}" | info
cat "${ENV}" | clean-credentials | info
# shellcheck disable=SC1090
source "${ENV}"
touch /tmp/pfsense-backup.started-at

# Add our cron entry, and direct stdout & stderr to Docker commands stdout
COMMAND=${COMMAND:-/usr/local/bin/backup}
info "installing cron.d entry: ${COMMAND}"
(mkdir -pv /var/spool/cron/crontabs && chmod -c 0755 /var/spool/cron/crontabs) | info
echo "${CRON_EXPRESSION} ${COMMAND} 2>&1" > /var/spool/cron/crontabs/root && chmod -c 0600 /var/spool/cron/crontabs/root | info
info "crontab: $(cat /var/spool/cron/crontabs/root)"

info "handing the reins over to cron daemon"
crond -l 2 -f
